### ISSUE TITLE
Wingolog.org posts have missing paragraphs in their content

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/website2org#10]
Hello!  Not to pester you with ongoing breakage reports on niche-websites, but, I just tested `website2org-temp` on [this URL](https://wingolog.org/archives/2017/03/06/its-probably-spam), and I am getting quite a few paragraphs in the body of the blog post content missing.  Here are examples, the left screen is the page rendering in Tor Browser, while the right screen is emacs running `website2org-temp` in a buffer:

![ss2](https://github.com/user-attachments/assets/3045b828-1ff3-4c2f-99b6-b88ddfb9b34c)
![ss1](https://github.com/user-attachments/assets/b0ca34ae-392c-450b-ae4e-7f4ef92e9548)

**Comment by k4r4b3y** [comment]
Here's another blog using the same blog engine ([Tekuti](https://github.com/wingo/tekuti)): https://blog.ryuslash.org/archives/2023/07/10/switch-todo-state-when-clocking-in

In that URL, too, I see that the paragraph that begins with the sentence, `This means that there are 4 sequences I've set up.` is missing from the `website2org-temp` buffer.

**Comment by rtrppl** [comment]
No worries about pestering but given the time of the year it might take a few days before I get to it. :)

**Comment by k4r4b3y** [comment]
> given the time of the year it might take a few days before I get to it. :)

Absolutely understandable.  Consider my issue threads here as "noting down the issues I come across with website2org tool" -- I don't want to come off as forcing any sort of obligation on you.

**Comment by rtrppl** [comment]
No worries. The issue should be fixed in the latest release (0.2.4). It feels a bit like Whac-A-Mole - as soon as one thing is fixed, another one emerges. This might be related to the very structure of the project. At one point I might have to do proper parsing and not use regexp+elisp for polishing.

**Comment by k4r4b3y** [comment]
Yeah this seems to work better.  However, in the wingolog.org link, the single paragraph after the `an aside` segment doesn't show up still.  Do you have an idea why this might be?

**Comment by rtrppl** [comment]
It should be fixed now. In that paragraph there was a link that had `<tt>` and `</tt>` tags in the text. This tricked the regexp into assuming there was something broken and hence the whole "line" was removed.

**Comment by k4r4b3y** [comment]
yep, it is fixed, thank you.
