### ISSUE TITLE
Feature request: include links to image files in the org document

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/website2org#5]
I run the `website2org-temp` function and give it the url: https://www.alexmurrell.co.uk/articles/the-age-of-average

The resulting org document shows no indication whether there were image files in the original webpage.  Instead of silently ignoring the image files in the original resource, it would be nice if `website2org` could insert a link to the image files in the original webpage resource.  See the following image for a comparison of eww rendering (left) and the `website2org-temp` file of the same webpage (right):

![ss](https://github.com/user-attachments/assets/083dff75-3361-4213-91e4-f9395071aaef)

**Comment by rtrppl** [comment]
I had something like this before but unfortunately it is not trivial (images, links and <style> etc are often interfering with each other). Might still add it at a later point.

**Comment by k4r4b3y** [comment]
Were you parsing for `<figure>` ?  Perhaps looking for known image file extensions (jpg,jpeg,png,avif,gif,webp,etc) would be more manageable?

**Comment by rtrppl** [comment]
No, I am only processing `<img>` tags. These are a bit different than "pure" text blocks and sometimes are intertwined with them. Anyhow, I think I found a way to do this. The first draft is in the development branch. I will do some more testing and then push it to main.

![Bildschirmfoto 2024-12-18 um 20 16 52](https://github.com/user-attachments/assets/8fc7914c-1a64-40bb-8bae-8f588696318f)

**Comment by k4r4b3y** [comment]
Looking good!  Let me check the development branch.

**Comment by k4r4b3y** [comment]
While testing with [this page](https://dark.fi/insights/anonymous-engineering.html) I noticed that when the image links are provided as relative links (ie, `img/anonymous-engineering/p2p.png`), the resulting image link also takes the form `img/anonymous-engineering/p2p.png`, while the correct link is `https://dark.fi/insights/img/anonymous-engineering/p2p.png`.

Do you think this can be fixed?

**Comment by k4r4b3y** [comment]
Maybe with a simple if-else check:

1. IF the image link starts with `https://`, THEN simply use the given https link
2. IF the image link doesn't start with `https://`, THEN simply append the given path to the last `/` portion part of the base url.

* So, in the case of given url: https://dark.fi/insights/anonymous-engineering.html

`website2org-temp` function sees the `img/anonymous-engineering/p2p.png` as the link given for the `<img>` tag element.  Since this link doesn't start with `https://`, the function takes the given url, and goes backwards from the right-most side of the url, until it hits the first `/`, which is `https://dark.fi/insights/`.  And it appends the `<img>` tag link to this portion of the given url: `https://dark.fi/insights/` + `img/anonymous-engineering/p2p.png` == `https://dark.fi/insights/img/anonymous-engineering/p2p.png` -- which is the correct url pointing to the image file resource.

**Comment by k4r4b3y** [comment]
Just tested your latest commits to the development branch.  The image links in the dark.fi article link is working, as well as a handful of other websites that use relative urls for the links got working too.

I think we can merge these changes to the main and close this issue now.  Thanks for the work!

**Comment by rtrppl** [comment]
There is another issue with the dark.fi article that I had on my list and want fix before pushing to main. Some people write HTML by hand and for some (to me absurd) reason they press enter at the end of the line and not the end of a paragraph. My current code somehow cuts trailing whitespace, so some of the words in the dark.fi article are merged together.

**Comment by rtrppl** [comment]
I think the changes are mostly done for this one. I see some weird duplication of headlines on sites like the verge, and will check that tomorrow.

**Comment by k4r4b3y** [comment]
I noticed another edge case with our implementation of image link creation.  See this url: https://lukesmith.xyz/articles/blockchain-blasphemy/

There, the article uses the image links of the following form: `<img src="/pix/akashic.webp">` (**observe the leading forward-slash**)

This makes the image link to fail in its current logic.  I think we can also easily account for this case: IF the src link **begins** with a forward slash, THEN append the src link to the baseURL of the webpage.  So we have, baseURL: `https://lukesmith.xyz` + `/pix/akashic.webp` == `https://lukesmith.xyz/pix/akashic.webp` -- which is the correct image URL.

So, all in all we have 3 cases:

1. IF the image link begins with `http://`, THEN, use the link as it is
2. ELSE IF the image link begins with `/`, THEN, append the image link to the baseURL
3. ELSE, take the user's URL, start from its right-most end, and move to its left side until you come-across the first `/` slash in the user's URL.  THEN, append the image link after that forward slash.

I think that would cover all our cases.

**Comment by k4r4b3y** [comment]
This commit https://github.com/rtrppl/website2org/commit/a28bfb785243a718c0f08aa47938bbd6b50ce075 seems to have fixed my abovementioned issue with lukesmith website.

**Comment by rtrppl** [comment]
It is now all in main. Thanks for the rather non-standard sample pages. I use this tool mainly to track official sources with very few images. But having images in there is nice. I also changed and fixed several more issues, while already working on this.
