### ISSUE TITLE
Feature request: Handle the vertical bar and other illegal characters in webpage title

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/website2org#6]
Example URL: https://reactionwheel.net/2023/08/ai-and-the-structure-of-reasoning.html

Results in a title: `20241219134448-AI and the Structure of Reasoning | Reaction Wheel`, which results in the corresponding filename `20241219134448-AI_and_the_Structure_of_Reasoning_|_Reaction_Wheel`.

Now, that `|` (vertical bar) character might be working in linux, but I get errors with [syncthing](syncthing.net) when I try to sync my whole orgrr directory to android (for the purposes of reading it later with my Orgro app).

Cursory look [1] [2] at the syncthing forums suggests that vertical bar is an "illegal character", which, syncthing is unable to work with.

Converting that character to some non-illegal character (like underscore `_`) would allow me to sync my `website2org` files to android using syncthing.

[1]: https://forum.syncthing.net/t/add-illegal-characters-handling/15745

[2]: https://forum.syncthing.net/t/check-for-filenames-which-might-be-invalid-on-other-platforms/11113/7

**Comment by rtrppl** [comment]
Yes, I will do that. Sometimes the <title> tag of website also is way too long (probably SEO related), this should also be addressed.

**Comment by rtrppl** [comment]
Fixed in the latest development branch (the vertical bar seems to have been the only special character I was not checking for). Probably in main by tomorrow.
