### ISSUE TITLE
Body of the articles do not show up for Zero Hedge links

### ISSUE THREAD

**Issue by k4r4b3y** [rtrppl/website2org#8]
When I insert any zerohedge article from my elfeed feed, I only get the title of the article, not its body.  Example [link](https://www.zerohedge.com/technology/david-friedbergs-drone-conspiracy-chinese-psyop-crush-emerging-us-drone-economy)

Here's what I get when I call `website2org-temp` function on  this link:

```
#+title: Is 'Dronegate' A Chinese Psyop? | ZeroHedge
#+roam_key: https://www.zerohedge.com/technology/david-friedbergs-drone-conspiracy-chinese-psyop-crush-emerging-us-drone-economy

* Is 'Dronegate' A Chinese Psyop?
```

This is the totality of what the `website2org-temp` function returns into the temporary buffer.

----

I also use `wesbite2org` package for noting down articles to my local storage for reading them later inside emacs (with the help of `orgrr`) -- so it would be cool to see zerohedge supported.

**Comment by rtrppl** [comment]
It should be fixed now. The reason for this behaviour was a `<footer>` tag right after the `<h1>` headline. website2org aims to remove the footer (as it usually does not include any important info). This time the function was - perhaps - a bit too greedy.
